In [ ]:
!pip install numpy
!pip install tensorflow

In [4]:
import numpy as np
import tensorflow as tf

# Creation

In [5]:
x = np.array([1,2,3,4])
print('This is an vector: ', x)

This is an vector:  [1 2 3 4]


In [8]:
A = np.array([[1,2],[3,4],[5,6]])
print('This is an Matrix: ', A)

This is an Matrix:  [[1 2]
 [3 4]
 [5 6]]


In [10]:
tensor_A = tf.constant([[1,2], [3,4], [5,6]])
print('This is an Tensor: ', tensor_A)

This is an Tensor:  tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


# Addition

In [17]:
vec_1 = np.array([1, 2, 3, 4])
vec_2 = np.array([9, 8, 7, 6])

vec_add = vec_1 + vec_2

print('This is the addition of 2 vectors: ')
print(vec_add)

This is the addition of 2 vectors: 
[10 10 10 10]


In [18]:
mat_1 = np.array([[1, 2],[ 3, 4]])
mat_2 = np.array([[9, 8], [7, 6]])

mat_add = mat_1 + mat_2

print('This is the addition of 2 matrices:')
print(mat_add)

This is the addition of 2 matrices:
[[10 10]
 [10 10]]


In [19]:
ten_1 = tf.constant([[1, 2], [3, 4]])
ten_2 = tf.constant([[9, 8], [7, 6]])

ten_add = ten_1 + ten_2

print('This is the addition of 2 tensors: ')
print(ten_add)

This is the addition of 2 tensors: 
tf.Tensor(
[[10 10]
 [10 10]], shape=(2, 2), dtype=int32)


# Multiplication

In [20]:
vec_3 = np.array([1, 2, 3, 4])
vec_4 = np.array([9, 8, 7, 6])

vec_mul = vec_3 * vec_4

print('This is the multiplication of 2 vectors: ')
print(vec_mul)

This is the multiplication of 2 vectors: 
[ 9 16 21 24]


In [21]:
mat_3 = np.array([[1, 2], [3, 4]])
mat_4 = np.array([[9, 8], [7, 6]])

mat_mul = mat_3 * mat_4

print('This is the multiplication of 2 matrices: ')
print(mat_mul)

This is the multiplication of 2 matrices: 
[[ 9 16]
 [21 24]]


In [22]:
ten_3 = tf.constant([[1, 2], [3, 4]])
ten_4 = tf.constant([[9, 8], [7, 6]])

ten_mul = ten_3 * ten_4

print('This is the multiplication of 2 tensors: ')
print(ten_mul)

This is the multiplication of 2 tensors: 
tf.Tensor(
[[ 9 16]
 [21 24]], shape=(2, 2), dtype=int32)


## Multiplication between a vector and matrix
- matrix x vector / vector x matrix both gives a matrix

In [ ]:
vec_5 = np.array([1, 2, 3, 4])
mat_5 = np.array([[1, 2], [3, 4]])

mat_6 = vec_5 * mat_5

print('This is the multiplication of a matrix and a vector: ')
print(mat_6)

## Multiplication between vector and tensor:
- vector x tensor / tensor x vector both give tensor

In [28]:
vec_6 = np.array([1, 2])
ten_6 = tf.constant([[1, 2], [3, 4]])

ten_7 = vec_6 * ten_6

print('This is the multiplication of a vector and tensor: ')
print(ten_7)

This is the multiplication of a vector and tensor: 
tf.Tensor(
[[1 4]
 [3 8]], shape=(2, 2), dtype=int32)


## Multiplication between matrix and tensor
- matrix x tensor / tensor x matrix gives tensor

In [30]:
mat_7 = np.array([[1, 2], [3, 4]])
ten_8 = tf.constant([[1, 2], [3, 4]])

ten_9 = ten_8 * mat_7

print('This is the multiplication of a matrix and tensor: ')
print(ten_9)

This is the multiplication of a matrix and tensor: 
tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)


In [ ]:
tf_x = tf.constant([1, 2, 3, 4, 5, 6], shape = [2, 3])
tf_y = tf.constant([4, 5, 6, 7, 8, 9], shape = [3, 2])

